ImportantCompanyApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ImportantCompanyApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ImportantCompanyApp/Pages/Index - Copy.cshtml.cs
using Azure.Storage.Queues;
using Azure.Storage.Queues.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImportantCompanyApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string WriteMessage { get; private set; } = "";
        protected string connectionString = "DefaultEndpointsProtocol=https;" 
            +"AccountName=newqueue9531;"
            +"AccountKey=wqwCvpjlKYDaJQ0NJcCrMaPn3Yt1SunwdCKcB62mGE7HG2VcTv6pv2fFw4Hk/+9w84YERU/+f5io+AStU8GTfA==;"
            +"EndpointSuffix=core.windows.net";
        protected string queueName = "ticketrequests";

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnPost()
        {
            GoWriteMessage();
        }

        public void GoWriteMessage()
        {
            
            QueueClient queue = new QueueClient(connectionString, queueName);
            queue.SendMessage("Hello, Azure!");
            WriteMessage += "Message written: Hello, Azure!\n";
        }

        public void OnGetGoReadMessage()
        {
            QueueClient queue = new QueueClient(connectionString, queueName);
            QueueMessage message = queue.ReceiveMessage().Value;
            if (message is not null)
            {
                WriteMessage += message.InsertedOn.ToString() + ": " + message.Body.ToString();
                queue.DeleteMessage(message.MessageId, message.PopReceipt);
            } else
            {
                WriteMessage += "No messages found";
            }
        }

    }
}

ImportantCompanyApp/Pages/Index.cshtml.cs
using Azure.Storage.Queues;
using Azure.Storage.Queues.Models;

using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ImportantCompanyApp.Pages
{
    public class IndexModel : PageModel
    {
        protected string connectionString = "<connection string from Azure Portal storage queue account>";
        protected string queueName = "ticketrequests";
        private readonly ILogger<IndexModel> _logger;
        public string WriteMessage { get; private set; } = "";

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnPost(string message)
        {
            GoWriteMessage(message);
        }

        public void GoWriteMessage(string message)
        {
            QueueClient queue = new QueueClient(connectionString, queueName);
            queue.SendMessage(message);
            WriteMessage += "Message written: " + message + "!\n";
        }

        public void OnGetGoReadMessage()
        {
            QueueClient queue = new QueueClient(connectionString, queueName);
            QueueMessage message = queue.ReceiveMessage().Value;
            if (message is not null)
            {
                WriteMessage += message.InsertedOn.ToString() + ": " + message.Body.ToString();
                queue.DeleteMessage(message.MessageId, message.PopReceipt);
            }
            else
            {
                WriteMessage += "No messages found.";
            }
        }
    }
}

ImportantCompanyApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImportantCompanyApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ImportantCompanyApp/Pages/Index - Copy.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    .message {
        width: 50%
    }
</style>

<div class="text-center">
    <h1 class="display-4">Important Company App Messaging Tool</h1>
    <br /><br /><br />
    <form method="post" action="">
        Message: <input type="text" class="message" id="message" name="message" value="Something really important." /><br />
        <input type="submit" value="Write Message" />
    </form>
    @Model.WriteMessage
    <br /><br /><br />
    <hr />
    <br /><br /><br />
    <a asp-page="Index" asp-page-handler="GoReadMessage">

        Read Message

    </a>

</div>

ImportantCompanyApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    .message {
        width: 50%
    }
</style>

<div class="text-center">
    <h1 class="display-4">Important Company App Messaging Tool</h1>
    <br /><br /><br />
    <form method="post" action="">
        Message: <input type="text" class="message" id="message" name="message" value="Something really important." /><br />
        <input type="submit" value="Write Message" />
    </form>
    @Model.WriteMessage
    <br /><br /><br />
    <hr />
    <br /><br /><br />
    <a asp-page="Index" asp-page-handler="GoReadMessage">

        Read Message

    </a>

</div>

ImportantCompanyApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImportantCompanyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ImportantCompanyApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ImportantCompanyApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>